<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StackRadius.Common\StackRadius.Common.csproj" />
    <ProjectReference Include="..\StackRadius.Entity\StackRadius.Entity.csproj" />
  </ItemGroup>

</Project>
