<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
 	<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> 
	<TargetFramework>net8.0</TargetFramework>	
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StackRadius.Repository\StackRadius.Repository.csproj" />
    <ProjectReference Include="..\StackRadius.Service\StackRadius.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Downloads\" />
  </ItemGroup>

</Project>
