using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace StackRadius.Entity
{
    public class ClientProfileModel : JSONBaseClass
    {
        public string Mode { get; set; }
        public string auth_email_sent { get; set; } // "Y",
        public string auth_status { get; set; } // "SUCCESS",
        public string member_code { get; set; } // "1006168",
        public string client_code { get; set; } // "5011503965",
        public string migrated_ucc { get; set; } // "N",
        public string ucc_status { get; set; } // "Active",
        public string ucc_remediation { get; set; } // " ",
        public string primary_holder_name { get; set; } // "GOBI S",
        public string primary_holder_dob { get; set; } // "20/10/1980",
        public string tax_status { get; set; } // "INDIVIDUAL",
        public string gender { get; set; } // "MALE",
        public string holding_nature { get; set; } // "ANYONE OR SURVIVOR",
        public string second_holder_name { get; set; } // "REVATHI KRISHNAMURTHY",
        public string third_holder_name { get; set; } // " ",
        public string guardian_name { get; set; } // " ",
        public string primary_holder_pan { get; set; } // "APOPG4050R",
        public string primary_holder_kyc_checked { get; set; } // "Y",
        public string primary_holder_kyc_status { get; set; } // "07 - KYC Validated",
        public string primary_holder_kyc_status_remarks { get; set; } // " ",
        public string second_holder_pan { get; set; } // "AUTPK2320C",
        public string second_holder_kyc_checked { get; set; } // "Y",
        public string second_holder_kyc_status { get; set; } // "07 - KYC Validated",
        public string second_holder_kyc_status_remarks { get; set; } // " ",
        public string third_holder_pan { get; set; } // " ",
        public string third_holder_kyc_checked { get; set; } // " ",
        public string third_holder_kyc_status { get; set; } // " ",
        public string third_holder_kyc_status_remarks { get; set; } // " ",
        public string guardian_pan { get; set; } // " ",
        public string guardian_kyc_checked { get; set; } // " ",
        public string guardian_kyc_status { get; set; } // " ",
        public string guardian_kyc_status_remark { get; set; } // " ",
        public string created_by { get; set; } // "FUTURE DYNAMICS F P",
        public string created_at { get; set; } // "20/08/2018 15:12:32",
        public string first_holder_fatca_exists { get; set; } // "Y",
        public string first_holder_fatca_image_exists { get; set; } // "N",
        public string first_holder_fatca_cams_upload_status { get; set; } // "UPLOADED",
        public string first_holder_fatca_cams_response_status { get; set; } // "ACCEPTED",
        public string first_holder_fatca_cams_remarks { get; set; } // " ",
        public string first_holder_fatca_kfin_upload_status { get; set; } // "UPLOADED",
        public string first_holder_fatca_kfin_response_status { get; set; } // "ACCEPTED",
        public string first_holder_fatca_kfin_remarks { get; set; } // " ",
        public string first_holder_normal_aof_exists { get; set; } // "Y",
        public string first_holder_normal_aof_cams_upload_status { get; set; } // "UPLOADED",
        public string first_holder_normal_aof_cams_response_status { get; set; } // "ACCEPTED",
        public string first_holder_normal_aof_cams_remarks { get; set; } // "MIG",
        public string first_holder_normal_aof_kfin_upload_status { get; set; } // "UPLOADED",
        public string first_holder_normal_aof_kfin_response_status { get; set; } // "ACCEPTED",
        public string first_holder_normal_aof_kfin_remarks { get; set; } // "MIG",
        public string first_holder_direct_aof_exists { get; set; } // "N",
        public string first_holder_direct_aof_cams_upload_status { get; set; } // " ",
        public string first_holder_direct_aof_cams_response_status { get; set; } // " ",
        public string first_holder_direct_aof_cams_remarks { get; set; } // " ",
        public string first_holder_direct_aof_kfin_upload_status { get; set; } // " ",
        public string first_holder_direct_aof_kfin_response_status { get; set; } // " ",
        public string first_holder_direct_aof_kfin_remarks { get; set; } // " ",
        public string first_holder_eLog_exists { get; set; } // "Y",
        public string first_holder_eLog_cams_upload_status { get; set; } // "PENDING",
        public string first_holder_eLog_cams_response_status { get; set; } // " ",
        public string first_holder_eLog_cams_remarks { get; set; } // " ",
        public string first_holder_eLog_kfin_upload_status { get; set; } // "PENDING",
        public string first_holder_eLog_kfin_response_status { get; set; } // " ",
        public string first_holder_eLog_kfin_remarks { get; set; } // " ",
        public string first_holder_email { get; set; } // "GOBEEMECH@GMAIL.COM",
        public string first_holder_mobile_no { get; set; } // "9600830881",
        public string first_holder_auth_status { get; set; } // "SUCCESS",
        public string first_holder_auth_remarks { get; set; } // " ",
        public string first_holder_auth_datetime { get; set; } // "05/03/2026 12:22:14",
        public string second_holder_fatca_exists { get; set; } // "Y",
        public string second_holder_fatca_image_exists { get; set; } // "N",
        public string second_holder_fatca_cams_upload_status { get; set; } // "UPLOADED",
        public string second_holder_fatca_cams_response_status { get; set; } // "ACCEPTED",
        public string second_holder_fatca_cams_remarks { get; set; } // " ",
        public string second_holder_fatca_kfin_upload_status { get; set; } // "UPLOADED",
        public string second_holder_fatca_kfin_response_status { get; set; } // "ACCEPTED",
        public string second_holder_fatca_kfin_remarks { get; set; } // " ",
        public string second_holder_normal_aof_exists { get; set; } // "Y",
        public string second_holder_normal_aof_cams_upload_status { get; set; } // "UPLOADED",
        public string second_holder_normal_aof_cams_response_status { get; set; } // "ACCEPTED",
        public string second_holder_normal_aof_cams_remarks { get; set; } // "MIG",
        public string second_holder_normal_aof_kfin_upload_status { get; set; } // "UPLOADED",
        public string second_holder_normal_aof_kfin_response_status { get; set; } // "ACCEPTED",
        public string second_holder_normal_aof_kfin_remarks { get; set; } // "MIG",
        public string second_holder_direct_aof_exists { get; set; } // "N",
        public string second_holder_direct_aof_cams_upload_status { get; set; } // " ",
        public string second_holder_direct_aof_cams_response_status { get; set; } // " ",
        public string second_holder_direct_aof_cams_remarks { get; set; } // " ",
        public string second_holder_direct_aof_kfin_upload_status { get; set; } // " ",
        public string second_holder_direct_aof_kfin_response_status { get; set; } // " ",
        public string second_holder_direct_aof_kfin_remarks { get; set; } // " ",
        public string second_holder_eLog_exists { get; set; } // "Y",
        public string second_holder_eLog_cams_upload_status { get; set; } // "UPLOADED",
        public string second_holder_eLog_cams_response_status { get; set; } // "ACCEPTED",
        public string second_holder_eLog_cams_remarks { get; set; } // "MIG",
        public string second_holder_eLog_kfin_upload_status { get; set; } // "UPLOADED",
        public string second_holder_eLog_kfin_response_status { get; set; } // "ACCEPTED",
        public string second_holder_eLog_kfin_remarks { get; set; } // "MIG",
        public string second_holder_email { get; set; } // "REVATHIKRISHNAMURTHY@GMAIL.COM",
        public string second_holder_mobile_no { get; set; } // "9791553919",
        public string second_holder_auth_status { get; set; } // "SUCCESS",
        public string second_holder_auth_remarks { get; set; } // " ",
        public string second_holder_auth_datetime { get; set; } // "05/03/2026 12:02:01",
        public string third_holder_fatca_exists { get; set; } // " ",
        public string third_holder_fatca_image_exists { get; set; } // " ",
        public string third_holder_fatca_cams_upload_status { get; set; } // " ",
        public string third_holder_fatca_cams_response_status { get; set; } // " ",
        public string third_holder_fatca_cams_remarks { get; set; } // " ",
        public string third_holder_fatca_kfin_upload_status { get; set; } // " ",
        public string third_holder_fatca_kfin_response_status { get; set; } // " ",
        public string third_holder_fatca_kfin_remarks { get; set; } // " ",
        public string third_holder_normal_aof_exists { get; set; } // " ",
        public string third_holder_normal_aof_cams_upload_status { get; set; } // " ",
        public string third_holder_normal_aof_cams_response_status { get; set; } // " ",
        public string third_holder_normal_aof_cams_remarks { get; set; } // " ",
        public string third_holder_normal_aof_kfin_upload_status { get; set; } // " ",
        public string third_holder_normal_aof_kfin_response_status { get; set; } // " ",
        public string third_holder_normal_aof_kfin_remarks { get; set; } // " ",
        public string third_holder_direct_aof_exists { get; set; } // " ",
        public string third_holder_direct_aof_cams_upload_status { get; set; } // " ",
        public string third_holder_direct_aof_cams_response_status { get; set; } // " ",
        public string third_holder_direct_aof_cams_remarks { get; set; } // " ",
        public string third_holder_direct_aof_kfin_upload_status { get; set; } // " ",
        public string third_holder_direct_aof_kfin_response_status { get; set; } // " ",
        public string third_holder_direct_aof_kfin_remarks { get; set; } // " ",
        public string third_holder_eLog_cams_upload_status { get; set; } // " ",
        public string third_holder_eLog_cams_response_status { get; set; } // " ",
        public string third_holder_eLog_cams_remarks { get; set; } // " ",
        public string third_holder_eLog_kfin_upload_status { get; set; } // " ",
        public string third_holder_eLog_kfin_response_status { get; set; } // " ",
        public string third_holder_eLog_kfin_remarks { get; set; } // " ",
        public string third_holder_eLog_exists { get; set; } // " ",
        public string third_holder_email { get; set; } // " ",
        public string third_holder_mobile_no { get; set; } // " ",
        public string third_holder_auth_status { get; set; } // " ",
        public string third_holder_auth_remarks { get; set; } // " ",
        public string third_holder_auth_datetime { get; set; } // " ",
        public string guardian_fatca_exists { get; set; } // " ",
        public string guardian_fatca_image_exists { get; set; } // " ",
        public string guardian_fatca_cams_upload_status { get; set; } // " ",
        public string guardian_fatca_cams_response_status { get; set; } // " ",
        public string guardian_fatca_cams_remarks { get; set; } // " ",
        public string guardian_fatca_kfin_upload_status { get; set; } // " ",
        public string guardian_fatca_kfin_response_status { get; set; } // " ",
        public string guardian_fatca_kfin_remarks { get; set; } // " ",
        public string guardian_normal_aof_exists { get; set; } // " ",
        public string guardian_direct_aof_exists { get; set; } // " ",
        public string guardian_normal_aof_cams_upload_status { get; set; } // " ",
        public string guardian_normal_aof_cams_response_status { get; set; } // " ",
        public string guardian_normal_aof_cams_remarks { get; set; } // " ",
        public string guardian_normal_aof_kfin_upload_status { get; set; } // " ",
        public string guardian_normal_aof_kfin_response_status { get; set; } // " ",
        public string guardian_normal_aof_kfin_remarks { get; set; } // " ",
        public string guardian_direct_aof_cams_upload_status { get; set; } // " ",
        public string guardian_direct_aof_cams_response_status { get; set; } // " ",
        public string guardian_direct_aof_cams_remarks { get; set; } // " ",
        public string guardian_direct_aof_kfin_upload_status { get; set; } // " ",
        public string guardian_direct_aof_kfin_response_status { get; set; } // " ",
        public string guardian_direct_aof_kfin_remarks { get; set; } // " ",
        public string guardian_elog_exists { get; set; } // " ",
        public string guardian_elog_cams_upload_status { get; set; } // " ",
        public string guardian_elog_cams_response_status { get; set; } // " ",
        public string guardian_elog_cams_remarks { get; set; } // " ",
        public string guardian_elog_kfin_upload_status { get; set; } // " ",
        public string guardian_elog_kfin_response_status { get; set; } // " ",
        public string guardian_elog_kfin_remarks { get; set; } // " ",
        public string guardian_auth_status { get; set; } // " ",
        public string guardian_auth_remarks { get; set; } // " ",
        public string guardian_auth_date_time { get; set; } // " ",
        public string demat_status { get; set; } // " ",
        public string dp_remarks { get; set; } // " ",
        public string default_dp { get; set; } // "PHYS",
        public string cdsl_dpid { get; set; } // " ",
        public string cdsl_cltid { get; set; } // " ",
        public string cmbp_id { get; set; } // " ",
        public string nsdl_dpid { get; set; } // " ",
        public string nsdl_cltid { get; set; } // " ",
        public string bank1_account_type { get; set; } // "SB",
        public string bank1_account_no { get; set; } // "000101614952",
        public string bank1_name { get; set; } // "ICICI BANK LIMITED",
        public string bank1_ifsc { get; set; } // "ICIC0000001",
        public string bank1_status { get; set; } // "ACTIVE",
        public string bank1_rejection_remarks { get; set; } // " ",
        public string bank2_account_type { get; set; } // " ",
        public string bank2_account_no { get; set; } // " ",
        public string bank2_name { get; set; } // " ",
        public string bank2_ifsc { get; set; } // " ",
        public string bank2_status { get; set; } // " ",
        public string bank2_rejection_remarks { get; set; } // " ",
        public string bank3_account_type { get; set; } // " ",
        public string bank3_account_no { get; set; } // " ",
        public string bank3_name { get; set; } // " ",
        public string bank3_ifsc { get; set; } // " ",
        public string bank3_status { get; set; } // " ",
        public string bank3_rejection_remarks { get; set; } // " ",
        public string bank4_account_type { get; set; } // " ",
        public string bank4_account_no { get; set; } // " ",
        public string bank4_name { get; set; } // " ",
        public string bank4_ifsc { get; set; } // " ",
        public string bank4_status { get; set; } // " ",
        public string bank4_rejection_remarks { get; set; } // " ",
        public string bank5_account_type { get; set; } // " ",
        public string bank5_account_no { get; set; } // " ",
        public string bank5_name { get; set; } // " ",
        public string bank5_ifsc { get; set; } // " ",
        public string bank5_status { get; set; } // " ",
        public string bank5_rejection_remarks { get; set; } // " "

        public List<SelectListItem> AMCCodeList { get; set; }
        public List<SelectListItem> ClientList { get; set; }        
    }
}
