using System;

namespace StackRadius.Entity
{
    public class NSEClientRegistrationModel : JSONBaseClass
    {
        public string reg_details { get; set; }   // jsonb in DB table
        public string client_code { get; set; }
        public string primary_holder_first_name { get; set; }
        public string? primary_holder_middle_name { get; set; }
        public string? primary_holder_last_name { get; set; }
        public string? tax_status { get; set; }
        public string? gender { get; set; }
        public DateTime primary_holder_dob_incorporation { get; set; }
        public string? occupation_code { get; set; }
        public string? holding_nature { get; set; }
        public string? second_holder_first_name { get; set; }
        public string? second_holder_middle_name { get; set; }
        public string? second_holder_last_name { get; set; }
        public string? third_holder_first_name { get; set; }
        public string? third_holder_middle_name { get; set; }
        public string? third_holder_last_name { get; set; }
        public DateTime second_holder_dob { get; set; }
        public DateTime third_holder_dob { get; set; }
        public string? guardian_first_name { get; set; }
        public string? guardian_middle_name { get; set; }
        public string? guardian_last_name { get; set; }
        public DateTime guardian_dob { get; set; }
        public string? primary_holder_pan_exempt { get; set; }
        public string? second_holder_pan_exempt { get; set; }
        public string? third_holder_pan_exempt { get; set; }
        public string? guardian_pan_exempt { get; set; }
        public string? primary_holder_pan { get; set; }
        public string? second_holder_pan { get; set; }
        public string? third_holder_pan { get; set; }
        public string? guardian_pan { get; set; }
        public string? primary_holder_exempt_category { get; set; }
        public string? second_holder_exempt_category { get; set; }
        public string? third_holder_exempt_category { get; set; }
        public string? guardian_exempt_category { get; set; }
        public string? client_type { get; set; }
        public string? pms { get; set; }
        public string? default_dp { get; set; }
        public string? cdsl_dpid { get; set; }
        public string? cdslcltid { get; set; }
        public string? cmbp_id { get; set; }
        public string? nsdldpid { get; set; }
        public string? nsdlcltid { get; set; }
        public string? account_type_1 { get; set; }
        public string? account_no_1 { get; set; }
        public string? micr_no_1 { get; set; }
        public string? ifsc_code_1 { get; set; }
        public string? default_bank_flag_1 { get; set; }
        public string? account_type_2 { get; set; }
        public string? account_no_2 { get; set; }
        public string? micr_no_2 { get; set; }
        public string? ifsc_code_2 { get; set; }
        public string? default_bank_flag_2 { get; set; }
        public string? account_type_3 { get; set; }
        public string? account_no_3 { get; set; }
        public string? micr_no_3 { get; set; }
        public string? ifsc_code_3 { get; set; }
        public string? default_bank_flag_3 { get; set; }
        public string? account_type_4 { get; set; }
        public string? account_no_4 { get; set; }
        public string? micr_no_4 { get; set; }
        public string? ifsc_code_4 { get; set; }
        public string? default_bank_flag_4 { get; set; }
        public string? account_type_5 { get; set; }
        public string? account_no_5 { get; set; }
        public string? micr_no_5 { get; set; }
        public string? ifsc_code_5 { get; set; }
        public string? default_bank_flag_5 { get; set; }
        public string? cheque_name { get; set; }
        public string? div_pay_mode { get; set; }
        public string? address_1 { get; set; }
        public string? address_2 { get; set; }
        public string? address_3 { get; set; }
        public string? city { get; set; }
        public string? state { get; set; }
        public double pincode { get; set; }
        public string? country { get; set; }
        public string? resi_phone { get; set; }
        public string? resi_fax { get; set; }
        public string? office_phone { get; set; }
        public string? office_fax { get; set; }
        public string? email { get; set; }
        public string? communication_mode { get; set; }
        public string? foreign_address_1 { get; set; }
        public string? foreign_address_2 { get; set; }
        public string? foreign_address_3 { get; set; }
        public string? foreign_address_city { get; set; }
        public string? foreign_address_pincode { get; set; }
        public string? foreign_address_state { get; set; }
        public string? foreign_address_country { get; set; }
        public string? foreign_address_resi_phone { get; set; }
        public string? foreign_address_fax { get; set; }
        public string? foreign_address_off_phone { get; set; }
        public string? foreign_address_off_fax { get; set; }
        public string? indian_mobile_no { get; set; }
        public string? primary_holder_kyc_type { get; set; }
        public string? primary_holder_ckyc_number { get; set; }
        public string? second_holder_kyc_type { get; set; }
        public string? second_holder_ckyc_number { get; set; }
        public string? third_holder_kyc_type { get; set; }
        public string? third_holder_ckyc_number { get; set; }
        public string? guardian_kyc_type { get; set; }
        public string? guardian_ckyc_number { get; set; }
        public string? primary_holder_kra_exempt_ref_no { get; set; }
        public string? second_holder_kra_exempt_ref_no { get; set; }
        public string? third_holder_kra_exempt_ref_no { get; set; }
        public string? guardian_exempt_ref_no { get; set; }
        public string? aadhaar_updated { get; set; }
        public string? mapin_id { get; set; }
        public string? paperless_flag { get; set; }
        public string? lei_no { get; set; }
        public DateTime lei_validity { get; set; }
        public string? mobile_declaration_flag { get; set; }
        public string? email_declaration_flag { get; set; }
        public string? second_holder_email { get; set; }
        public string? second_holder_email_declaration { get; set; }
        public string? second_holder_mobile { get; set; }
        public string? second_holder_mobiledeclaration { get; set; }
        public string? third_holder_email { get; set; }
        public string? third_holder_email_declaration { get; set; }
        public string? third_holder_mobile { get; set; }
        public string? third_holder_mobile_declaration { get; set; }
        public string? guardian_relation { get; set; }
        public string? nomination_opt { get; set; }
        public string? nomination_authentication { get; set; }
        public string? nominee_1_name { get; set; }
        public string? nominee_1_relationship { get; set; }
        public double nominee_1_applicable { get; set; }
        public string? nominee_1_minor_flag { get; set; }
        public DateTime nominee_1_dob { get; set; }
        public string? nominee_1_guardian { get; set; }
        public string? nominee_1_guardian_pan { get; set; }
        public string? nominee_1_identity_type { get; set; }
        public string? nominee_1_identity_number { get; set; }
        public string? nominee_1_email { get; set; }
        public string? nominee_1_mobile { get; set; }
        public string? nominee_1_address1 { get; set; }
        public string? nominee_1_address2 { get; set; }
        public string? nominee_1_address3 { get; set; }
        public string? nominee_1_city { get; set; }
        public string? nominee_1_pin { get; set; }
        public string? nominee_1_country { get; set; }
        public string? nominee_2_name { get; set; }
        public string? nominee_2_relationship { get; set; }
        public double nominee_2_applicable { get; set; }
        public DateTime nominee_2_dob { get; set; }
        public string? nominee_2_minor_flag { get; set; }
        public string? nominee_2_guardian { get; set; }
        public string? nominee_2_guardian_pan { get; set; }
        public string? nominee_2_identity_type { get; set; }
        public string? nominee_2_identity_number { get; set; }
        public string? nominee_2_email { get; set; }
        public string? nominee_2_mobile { get; set; }
        public string? nominee_2_address1 { get; set; }
        public string? nominee_2_address2 { get; set; }
        public string? nominee_2_address3 { get; set; }
        public string? nominee_2_city { get; set; }
        public string? nominee_2_pin { get; set; }
        public string? nominee_2_country { get; set; }
        public string? nominee_3_name { get; set; }
        public string? nominee_3_relationship { get; set; }
        public double nominee_3_applicable { get; set; }
        public DateTime nominee_3_dob { get; set; }
        public string? nominee_3_minor_flag { get; set; }
        public string? nominee_3_guardian { get; set; }
        public string? nominee_3_guardian_pan { get; set; }
        public string? nominee_3_identity_type { get; set; }
        public string? nominee_3_identity_number { get; set; }
        public string? nominee_3_email { get; set; }
        public string? nominee_3_mobile { get; set; }
        public string? nominee_3_address1 { get; set; }
        public string? nominee_3_address2 { get; set; }
        public string? nominee_3_address3 { get; set; }
        public string? nominee_3_city { get; set; }
        public string? nominee_3_pin { get; set; }
        public string? nominee_3_country { get; set; }
        public string? nominee_soa { get; set; }
        public string? second_holder_mobile_declaration { get; set; }
        public string? reg_id { get; set; }
        public string? reg_remark { get; set; }
        public string? reg_status { get; set; }
    }
}